const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript')
function load(file,deps={},env={}){
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,
 {module,exports:module.exports,require:n=>deps[n]||require(n),process:{env},URL,Date,Response,Request,AbortSignal,fetch:deps.fetch,console});return module.exports
}
const plans=load('lib/plans.ts')
const env={STRIPE_SOLO_MONTHLY_PRICE_ID:'price_solo29',STRIPE_PRO_MONTHLY_PRICE_ID:'price_pro59',NEXT_PUBLIC_APP_URL:'https://app.example.com',STRIPE_WEBHOOK_SECRET:'test',ANTHROPIC_API_KEY:'test'}
const billing=load('lib/billing.ts',{'./plans':plans},env)
function setup({subscriptions=[],source='stripe',locked=false,writeError=false,unknown=false}={}){
 const calls=[],sync=[]
 const admin={from(table){let action='read';const q={};for(const key of ['select','eq'])q[key]=(...args)=>{calls.push([table,key,...args]);return q};q.delete=()=>{action='delete';calls.push([table,'delete']);return q};q.maybeSingle=async()=>({data:unknown?null:{user_id:'owner',source,customer_id:'cus_owned'},error:null});q.then=(resolve)=>resolve({data:null,error:null});return q},async rpc(name,args){calls.push([name,args]);if(name==='hirely_sync_billing')sync.push(args);return {data:!locked,error:writeError&&name==='hirely_sync_billing'?{message:'failed'}:null}}}
 const stripe={subscriptions:{list:async args=>{calls.push(['stripe-list',args]);return {data:subscriptions,has_more:false}}}}
 return{admin,stripe,calls,sync}
}
function sub(status='active',price='price_pro59'){return{id:'sub_current',status,items:{data:[{price:{id:price},quantity:1,current_period_end:2000000000}]}}}
test('only configured Solo and Pro checkout prices are available',()=>{assert.equal(billing.checkoutPrice('solo').amount,2900);assert.equal(billing.checkoutPrice('pro').amount,5900);assert.throws(()=>billing.checkoutPrice('agency'));assert.throws(()=>billing.checkoutPrice('free'));assert.equal(billing.planForPrice('unknown'),null);assert.equal(billing.planForPrice('price_1TrVWtJYp8fgJBx4CqOBQ531'),'pro')})
test('webhook reconciliation reads current subscription and scopes the update to its owned customer',async()=>{const h=setup({subscriptions:[sub()]});await billing.syncCustomer(h.stripe,h.admin,'cus_owned');assert.equal(h.sync[0].paid_plan,'pro');assert.equal(h.sync[0].uid,'owner');assert.equal(h.sync[0].customer,'cus_owned');assert.equal(h.sync[0].subscription,'sub_current');assert.ok(h.calls.some(c=>c[0]==='hirely_billing_locks'&&c[1]==='delete'))})
test('repeated and delayed notifications converge to current cancellation, not old paid metadata',async()=>{const h=setup({subscriptions:[sub('canceled')]});await billing.syncCustomer(h.stripe,h.admin,'cus_owned');await billing.syncCustomer(h.stripe,h.admin,'cus_owned');assert.equal(h.sync.length,2);assert.ok(h.sync.every(s=>s.paid_plan==='free'&&s.subscription===null))})
test('manual grants survive Stripe notifications',async()=>{const h=setup({source:'manual',subscriptions:[sub('canceled')]});await billing.syncCustomer(h.stripe,h.admin,'cus_owned');assert.equal(h.sync.length,0);assert.equal(h.calls.some(c=>c[0]==='stripe-list'),false)})
test('unknown price, multiple active plans, or missing customer never grants access',async()=>{for(const config of [{subscriptions:[sub('active','bad')]},{subscriptions:[sub(),sub()]},{unknown:true}]){const h=setup(config);await assert.rejects(billing.syncCustomer(h.stripe,h.admin,'cus_owned'));assert.equal(h.sync.length,0)}})
test('concurrent and failed database updates request retries',async()=>{for(const config of [{locked:true},{writeError:true}]){const h=setup({...config,subscriptions:[sub()]});await assert.rejects(billing.syncCustomer(h.stripe,h.admin,'cus_owned'))}})
function webhook({signature=true,eventType='customer.subscription.updated',fails=false}={}){
 let calls=0;const route=load('app/api/stripe/webhook/route.ts',{'next/server':{NextResponse:Response},'@/lib/billing':{billingClients:()=>({stripe:{webhooks:{constructEvent:()=>{if(!signature)throw Error('invalid');return {type:eventType,data:{object:{customer:'cus_owned',metadata:{plan:'agency'}}}}}}},admin:{}}),syncCustomer:async()=>{calls++;if(fails)throw Error('db down')}}},env)
 return {run:()=>route.POST(new Request('https://test/webhook',{method:'POST',body:'payload'})),get calls(){return calls}}
}
test('invalid webhook signatures have no side effects',async()=>{const h=webhook({signature:false});assert.equal((await h.run()).status,400);assert.equal(h.calls,0)})
test('webhook storage failure is not acknowledged',async()=>{const h=webhook({fails:true});assert.equal((await h.run()).status,503)})
test('unsupported events are acknowledged without billing mutation',async()=>{const h=webhook({eventType:'customer.created'});assert.equal((await h.run()).status,200);assert.equal(h.calls,0)})
function checkout({anonymous=false,plan='solo',amount=2900,existing=false,open=false,managed=true,manual=false}={}){
 const calls=[];const admin={from(){return{select(){return this},eq(){return this},maybeSingle:async()=>({data:{customer_id:'cus_owned',source:manual?'manual':'stripe'},error:null})}}}
 const stripe={prices:{retrieve:async()=>({active:true,currency:'usd',unit_amount:amount,recurring:{interval:'month',interval_count:1,usage_type:'licensed'}})},billingPortal:{sessions:{create:async()=>{calls.push('portal');return{url:'https://stripe.test/portal'}}}},checkout:{sessions:{list:async()=>({data:open?[{id:'cs_open',mode:'subscription',managed_payments:{enabled:managed},metadata:{hirely_price:'price_solo29'},url:'https://stripe.test/existing'}]:[],has_more:false}),expire:async(id)=>{calls.push(['expired',id])},create:async(data)=>{calls.push(data);return{url:'https://stripe.test/new'}}}}}
 const route=load('app/api/stripe/checkout/route.ts',{'next/server':{NextResponse:Response},'@/lib/server-auth':{authenticate:async()=>anonymous?null:{user:{id:'owner'}}},'@/lib/billing':{...billing,billingClients:()=>({stripe,admin}),withBillingLock:async(_,uid,fn)=>{assert.equal(uid,'owner');return fn('lease')},listSubscriptions:async()=>existing?[{status:'active'}]:[]}},env)
 return{calls,run:()=>route.POST(new Request('https://test/checkout',{method:'POST',body:JSON.stringify({plan,userId:'attacker'})}))}
}
test('checkout rejects anonymous, Agency, and wrong configured prices',async()=>{for(const config of [{anonymous:true},{plan:'agency'},{amount:1900}]){const h=checkout(config);assert.ok((await h.run()).status>=400);assert.equal(h.calls.length,0)}})
test('checkout uses verified owner, correct price and existing app route',async()=>{const h=checkout();assert.equal((await h.run()).status,200);assert.equal(h.calls[0].client_reference_id,'owner');assert.equal(h.calls[0].line_items[0].price,'price_solo29');assert.equal(h.calls[0].success_url,'https://app.example.com/?upgraded=true');assert.equal(h.calls[0].subscription_data.trial_period_days,undefined);assert.equal(h.calls[0].managed_payments.enabled,true);assert.equal(h.calls[0].payment_method_types,undefined)})
test('existing subscriptions go to portal and open checkouts are reused',async()=>{const existing=checkout({existing:true});assert.equal((await(await existing.run()).json()).url,'https://stripe.test/portal');assert.deepEqual(existing.calls,['portal']);const open=checkout({open:true});assert.equal((await(await open.run()).json()).url,'https://stripe.test/existing');assert.equal(open.calls.length,0)})
test('complimentary owner cannot accidentally purchase another subscription',async()=>{const h=checkout({manual:true});assert.equal((await h.run()).status,503);assert.equal(h.calls.length,0)})
test('free and exhausted draft requests cannot call AI',async()=>{let fetched=0;const route=load('app/api/generate-drafts/route.ts',{'next/server':{NextResponse:Response},'@/lib/server-auth':{authenticate:async()=>({user:{id:'owner'},db:{rpc:async(name,args)=>{assert.equal(args.feature,'draft');return{data:false,error:null}}}})},fetch:async()=>{fetched++;throw Error('unexpected')}},env);assert.equal((await route.POST(new Request('https://test/drafts',{method:'POST',body:JSON.stringify({firstName:'Jane'})}))).status,402);assert.equal(fetched,0)})
test('legacy unmanaged checkout is expired before creating a Managed Payments session',async()=>{const h=checkout({open:true,managed:false});assert.equal((await(await h.run()).json()).url,'https://stripe.test/new');assert.deepEqual(h.calls[0],['expired','cs_open']);assert.equal(h.calls[1].managed_payments.enabled,true)})
