const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,deps={}){const module={exports:{}};const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,{module,exports:module.exports,require:n=>deps[n]||require(n),URL,URLSearchParams,Response,Request,AbortSignal,process:{env:{NEXT_PUBLIC_SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'test',HUNTER_API_KEY:'test'}},fetch:deps.fetch,console,Date});return module.exports}
const patterns=load('lib/email-patterns.ts'),plans=load('lib/plans.ts');
test('supports real company formats without accepting arbitrary templates',()=>{
 assert.equal(patterns.predictEmail('Jane','Smith','https://www.example.com/','{f}{last}'),'jsmith@example.com');
 assert.equal(patterns.predictEmail('José',"O’Neill",'example.com','{first}.{last}'),'jose.oneill@example.com');
 assert.equal(patterns.predictEmail('Jane','','example.com','{first}.{last}'),null);
 assert.equal(patterns.predictEmail('Jane','Smith','bad domain','{first}.{last}'),null);
 assert.equal(patterns.predictEmail('Jane','Smith','example.com','{unknown}'),null);
 assert.equal(patterns.identifyEmailPattern('Jane','Smith','jane.smith@example.com','example.com'),'{first}.{last}');
 assert.equal(patterns.identifyEmailPattern('Jane','Smith','janesmith@example.com','example.com'),'{first}{last}');
});
test('freshness and catch-all do not become verification',()=>{
 assert.equal(patterns.isFresh('2099-01-01'),false);
 assert.equal(patterns.isFresh('2020-01-01'),false);
 assert.equal(patterns.providerStatus('accept_all'),'accept_all');
 assert.equal(patterns.providerStatus('deliverable'),'unknown');
});
function harness({user=true,contact=null,cache=null,company=null,reserved=true,providerEmail="jane.smith@example.com",providerFail=false,providerThrows=false,usage=0,quotaError=false,reservationFails=false,providerBudget='reserved',exaConfigured=false,exaEmail=null,exaBudget='reserved',anymailConfigured=false,anymailResult={kind:'none',creditsCharged:0},anymailBudget='reserved'}={}){
 const writes=[],calls=[],reservedProviders=[];let fetched=0,credits=0,providerReservations=0,providerReleases=0,providerEvidence=0,exaSearches=0,anymailSearches=0;
 const db={from(table){let action='read';const chain=new Proxy({}, {get(_,key){
  if(key==='update'||key==='upsert'||key==='insert')return data=>{action=key;writes.push({table,data});return chain};
  const result=()=>({data:table==='contacts'?(action==='read'?contact:{id:contact?.id}):table==='email_resolutions'?cache:table==='company_cache'?company:table==='hirely_limits'?{email_limit:reserved?10:0}:table==='hirely_usage'?{used:usage}:null,error:quotaError&&table==='hirely_limits'?{message:'unavailable'}:null});
  if(key==='then')return(resolve,reject)=>Promise.resolve(result()).then(resolve,reject);
  if(key==='single'||key==='maybeSingle')return async()=>result();
  return(...args)=>{calls.push([table,key,...args]);return chain}
 }});return chain},async rpc(name){calls.push(['rpc',name]);if(name==='get_hirely_entitlements')return {data:{plan:'solo',email_limit:reserved?10:0,email_used:usage},error:quotaError?{message:'unavailable'}:null};credits++;return {data:reserved&&!reservationFails,error:null}}};
 const resolver=load('lib/resolve-email.ts',{'next/server':{NextResponse:{json:(body,init)=>Response.json(body,init)}},'./server-auth':{authenticate:async()=>user?{db,user:{id:'u1'}}:null},'./email-patterns':patterns,'./plans':plans,'./company-data':{approvedCompanyPattern:async()=>company?.[0]?.data?{...company[0].data,evidence:'Test reviewed pattern'}:null,recordCompanySearch:async()=>{},recordProviderPatternEvidence:async()=>{providerEvidence++}},'./provider-budget':{reserveProviderCredit:async provider=>{providerReservations++;reservedProviders.push(provider);return provider==='exa'?exaBudget:provider==='anymail'?anymailBudget:providerBudget},releaseProviderCredit:async()=>{providerReleases++}},'./exa-email':{exaEmailSearchConfigured:()=>exaConfigured,findPublishedEmailWithExa:async()=>{exaSearches++;return exaEmail}},'./anymail-email':{anymailEmailSearchConfigured:()=>anymailConfigured,findVerifiedEmailWithAnymail:async()=>{anymailSearches++;return anymailResult}},fetch:async()=>{fetched++;if(providerThrows)throw new Error('timeout');if(providerFail)return Response.json({}, {status:502});return Response.json({data:{email:providerEmail,domain:'example.com',status:'accept_all',score:93,sources:[{uri:'https://example.com/team'}]}})}}).resolveEmail;
 const run=body=>resolver(new Request('http://localhost/api/enrich',{method:'POST',body:JSON.stringify(body)}));
 return{run,writes,calls,reservedProviders,get fetched(){return fetched},get credits(){return credits},get providerReservations(){return providerReservations},get providerReleases(){return providerReleases},get providerEvidence(){return providerEvidence},get exaSearches(){return exaSearches},get anymailSearches(){return anymailSearches}};
}
const person={action:'find',allowPaid:true,firstName:'Jane',lastName:'Smith',company:'Example'};
test('anonymous callers cannot use providers',async()=>{const h=harness({user:false});assert.equal((await h.run(person)).status,401);assert.equal(h.fetched,0)});
test('another users contact cannot be enriched',async()=>{const h=harness();assert.equal((await h.run({...person,contactId:5})).status,404);assert.equal(h.fetched,0);assert.ok(h.calls.some(c=>c[1]==='eq'&&c[2]==='user_id'&&c[3]==='u1'))});
test('company pattern consumes one Hirely credit without a provider call',async()=>{const h=harness({company:[{data:{domain:'example.com',pattern:'{first}.{last}'}}]});const d=await(await h.run(person)).json();assert.equal(d.email,'jane.smith@example.com');assert.equal(d.emailStatus,'predicted');assert.equal(d.confidence,null);assert.equal(h.fetched,0);assert.equal(h.credits,1)});
test('database miss calls provider once, charges once and saves result',async()=>{const h=harness();const d=await(await h.run(person)).json();assert.equal(d.email,'jane.smith@example.com');assert.equal(h.fetched,1);assert.equal(h.credits,1);assert.ok(h.writes.some(w=>w.table==='email_resolutions'))});
test('successful provider result consumes global budget and queues pattern evidence',async()=>{const h=harness();await h.run(person);assert.equal(h.providerReservations,1);assert.equal(h.providerReleases,0);assert.equal(h.providerEvidence,1)});
test('Exa public-source success is used before Hunter and saved as pattern evidence',async()=>{const h=harness({exaConfigured:true,exaEmail:{email:'jane.smith@example.com',domain:'example.com',pattern:'{first}.{last}',sourceUrl:'https://example.com/team'}});const d=await(await h.run(person)).json();assert.equal(d.email,'jane.smith@example.com');assert.equal(d.source,'exa_public_source');assert.equal(h.exaSearches,1);assert.equal(h.fetched,0);assert.deepEqual(h.reservedProviders,['exa']);assert.equal(h.providerEvidence,1);assert.equal(h.credits,1)});
test('an Exa miss or exhausted Exa budget falls through to Hunter',async()=>{for(const options of [{exaConfigured:true,exaEmail:null},{exaConfigured:true,exaBudget:'exhausted'}]){const h=harness(options);const d=await(await h.run(person)).json();assert.equal(d.source,'hunter_finder');assert.equal(h.fetched,1);assert.equal(h.reservedProviders.at(-1),'hunter')}});
test('Anymail Finder valid result is used after Exa and before Hunter',async()=>{const h=harness({exaConfigured:true,exaEmail:null,anymailConfigured:true,anymailResult:{kind:'found',email:'jane.smith@example.com',domain:'example.com',creditsCharged:1}});const d=await(await h.run(person)).json();assert.equal(d.source,'anymail_finder');assert.equal(d.emailStatus,'valid');assert.equal(h.anymailSearches,1);assert.equal(h.fetched,0);assert.deepEqual(h.reservedProviders,['exa','anymail']);assert.equal(h.providerEvidence,1);assert.equal(h.credits,1)});
test('free Anymail Finder miss releases its reservation and falls through to Hunter',async()=>{const h=harness({anymailConfigured:true,anymailResult:{kind:'none',creditsCharged:0}});const d=await(await h.run(person)).json();assert.equal(d.source,'hunter_finder');assert.equal(h.anymailSearches,1);assert.equal(h.fetched,1);assert.deepEqual(h.reservedProviders,['anymail','hunter']);assert.equal(h.providerReleases,1)});
test('paid lookup needs explicit opt-in and quota',async()=>{const h=harness({reserved:false});assert.equal((await h.run({...person,action:'find',allowPaid:false})).status,400);assert.equal((await h.run({...person,action:'find',allowPaid:true})).status,402);assert.equal(h.fetched,0)});
test('verification keeps accept-all separate from valid',async()=>{const h=harness({contact:{id:5,first_name:'Jane',last_name:'Smith',company:'Example',email:'jane.smith@example.com',email_status:'predicted'}});const d=await(await h.run({contactId:5,action:'verify',allowPaid:true})).json();assert.equal(d.emailStatus,'accept_all');assert.equal(h.fetched,1);assert.equal(h.writes.find(w=>w.table==='contacts').data.email_status,'accept_all')});
test('fresh verified cache avoids repeat paid calls and is not treated as a Finder discovery',async()=>{const h=harness({cache:{email:'jane.smith@example.com',status:'valid',source:'hunter_verifier',created_at:new Date().toISOString(),checked_at:new Date().toISOString()}});const d=await(await h.run({...person,action:'find',allowPaid:true})).json();assert.equal(d.emailStatus,'valid');assert.equal(h.fetched,0);assert.equal(h.credits,1);assert.equal(h.providerEvidence,0)});

test('cached results cannot bypass exhausted credits',async()=>{const h=harness({reserved:false,cache:{email:'jane@example.com',status:'valid',created_at:new Date().toISOString(),checked_at:new Date().toISOString()}});assert.equal((await h.run(person)).status,402);assert.equal(h.fetched,0);assert.equal(h.writes.length,0)});
test('legacy prediction action cannot bypass credit consent',async()=>{const h=harness();assert.equal((await h.run({...person,action:'predict',allowPaid:false})).status,400);assert.equal(h.credits,0);assert.equal(h.fetched,0)});
test('fresh unverified provider result is reused and queued as a pattern candidate',async()=>{const h=harness({cache:{email:'jane@example.com',status:'unknown',source:'hunter_finder',created_at:new Date().toISOString()}});const d=await(await h.run(person)).json();assert.equal(d.emailStatus,'unknown');assert.equal(h.credits,1);assert.equal(h.fetched,0);assert.equal(h.providerEvidence,1)});
test('fresh Anymail Finder result is reused and queued as a pattern candidate',async()=>{const h=harness({cache:{email:'jane@example.com',status:'valid',source:'anymail_finder',created_at:new Date().toISOString(),checked_at:new Date().toISOString()}});const d=await(await h.run(person)).json();assert.equal(d.emailStatus,'valid');assert.equal(h.fetched,0);assert.equal(h.providerEvidence,1)});

test('no-result search uses zero credits',async()=>{const h=harness({providerEmail:null});const d=await(await h.run(person)).json();assert.equal(d.creditsUsed,0);assert.equal(h.credits,0);assert.equal(h.fetched,1);assert.equal(h.writes.length,0)});
test('no-result search releases the global provider reservation',async()=>{const h=harness({providerEmail:null});await h.run(person);assert.equal(h.providerReservations,1);assert.equal(h.providerReleases,1)});
test('provider failure uses zero credits',async()=>{const h=harness({providerFail:true});const response=await h.run(person);assert.equal(response.status,502);assert.equal(h.credits,0);assert.match((await response.json()).error,/No credit used/)});
test('provider timeout uses zero credits',async()=>{const h=harness({providerThrows:true});const response=await h.run(person);assert.equal(response.status,502);assert.equal(h.credits,0);assert.match((await response.json()).error,/No credit used/)});

test('exhausted current-month usage stops provider calls',async()=>{const h=harness({usage:10});assert.equal((await h.run(person)).status,402);assert.equal(h.fetched,0);assert.equal(h.credits,0);assert.ok(h.calls.some(c=>c[0]==='rpc'&&c[1]==='get_hirely_entitlements'))});
test('quota lookup failure stops provider calls without charging',async()=>{const h=harness({quotaError:true});assert.equal((await h.run(person)).status,503);assert.equal(h.fetched,0);assert.equal(h.credits,0)});
test('global provider budget exhaustion stops Hunter before a paid call',async()=>{const h=harness({providerBudget:'exhausted'});const response=await h.run(person);assert.equal(response.status,503);assert.equal(h.fetched,0);assert.match((await response.json()).error,/budget reached/i)});
test('malformed provider email is not a billable result',async()=>{for(const email of [' ',{},'not-an-email']){const h=harness({providerEmail:email});assert.equal((await(await h.run(person)).json()).creditsUsed,0);assert.equal(h.credits,0)}});
test('atomic reservation prevents a result from bypassing a concurrent quota exhaustion',async()=>{const h=harness({reservationFails:true});assert.equal((await h.run(person)).status,402);assert.equal(h.fetched,1);assert.equal(h.credits,1)});
