const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const trashModule={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/contact-trash.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:trashModule,exports:trashModule.exports,Date});
function harness({user={id:'owner'},authError=null,missing=false,writeError=false}={}){
 const calls=[];let verified=0;
 const db={auth:{getUser:async()=>{verified++;return {data:{user},error:authError}},getSession:()=>{throw Error('Unverified session must not authorize requests')}},from(table){calls.push(['from',table]);const q={};for(const key of ['select','insert','update','delete','eq','order','is','not'])q[key]=(...args)=>{calls.push([key,...args]);return q};q.single=q.maybeSingle=async()=>({data:missing?null:{id:'contact'},error:writeError?{message:'failed'}:null});q.then=(resolve,reject)=>Promise.resolve({data:[],error:null}).then(resolve,reject);return q;}};
 const module={exports:{}};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/leads/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,URL,require:n=>({'@/lib/contact-trash':trashModule.exports,'@supabase/ssr':{createServerClient:()=>db},'next/headers':{cookies:()=>({getAll:()=>[],set:()=>{}})},'next/server':{NextResponse:{json:(b,o)=>Response.json(b,o)}}}[n]),process:{env:{}},console});
 return {calls,get verified(){return verified},run:(method,body,raw=false)=>module.exports[method](new Request('http://localhost/api/leads',{method,...(method==='GET'?{}:{body:raw?body:JSON.stringify(body)})}))};
}
for(const method of ['GET','POST','PATCH','DELETE'])test(`${method} rejects unverified users before database access`,async()=>{for(const opts of [{user:null},{authError:{message:'expired'}}]){const h=harness(opts);assert.equal((await h.run(method,{id:'contact',first_name:'Jane',last_name:'Smith'})).status,401);assert.equal(h.verified,1);assert.equal(h.calls.length,0)}});
for(const method of ['POST','PATCH','DELETE'])test(`${method} rejects malformed or nonobject JSON`,async()=>{for(const body of ['{','null','[]','"text"']){const h=harness();assert.equal((await h.run(method,body,true)).status,400);assert.equal(h.calls.length,0)}});
test('PATCH rejects ownership and verification changes',async()=>{for(const fields of [{user_id:'other'},{email_status:'verified'},{created_at:'2020-01-01'},{company:{}},{first_name:' '}]){const h=harness();assert.equal((await h.run('PATCH',{id:'contact',...fields})).status,400);assert.equal(h.calls.length,0)}});
test('PATCH allows ordinary edits and scopes them to the verified owner',async()=>{const h=harness();assert.equal((await h.run('PATCH',{id:'contact',company:'Example'})).status,200);assert.ok(h.calls.some(c=>c[0]==='eq'&&c[1]==='user_id'&&c[2]==='owner'));assert.ok(h.calls.some(c=>c[0]==='eq'&&c[1]==='id'&&c[2]==='contact'))});
test('manual email edits clear old verification',async()=>{const h=harness();await h.run('PATCH',{id:'contact',email:'new@example.com'});const value=h.calls.find(c=>c[0]==='update')[1];assert.equal(value.email_status,'unverified');assert.equal(value.email_checked_at,null);assert.equal(value.email_evidence,'')});
test('POST uses authenticated owner and ignores caller ownership',async()=>{const h=harness();assert.equal((await h.run('POST',{first_name:'Jane',last_name:'Smith',user_id:'other'})).status,201);assert.equal(h.calls.find(c=>c[0]==='insert')[1].user_id,'owner')});
test('GET and DELETE retain owner filters',async()=>{for(const method of ['GET','DELETE']){const h=harness();assert.equal((await h.run(method,{id:'contact'})).status,200);assert.ok(h.calls.some(c=>c[0]==='eq'&&c[1]==='user_id'&&c[2]==='owner'))}});
test('DELETE missing ID cannot reach database',async()=>{const h=harness();assert.equal((await h.run('DELETE',{})).status,400);assert.equal(h.calls.length,0)});

test('DELETE moves to Trash and never performs hard delete',async()=>{const h=harness();assert.equal((await h.run('DELETE',{id:'contact'})).status,200);assert.ok(h.calls.some(c=>c[0]==='update'&&typeof c[1].deleted_at==='string'));assert.ok(h.calls.some(c=>c[0]==='is'&&c[1]==='deleted_at'&&c[2]===null));assert.equal(h.calls.some(c=>c[0]==='delete'),false)});
test('restore only clears deletion on an owned trashed row',async()=>{const h=harness();assert.equal((await h.run('PATCH',{id:'contact',action:'restore'})).status,200);assert.deepEqual(JSON.parse(JSON.stringify(h.calls.find(c=>c[0]==='update')[1])),{deleted_at:null});assert.ok(h.calls.some(c=>c[0]==='not'&&c[1]==='deleted_at'));assert.ok(h.calls.some(c=>c[0]==='eq'&&c[1]==='user_id'&&c[2]==='owner'))});
test('stale or failed Trash/Restore request cannot report success',async()=>{for(const config of [{missing:true},{writeError:true}])for(const [method,body] of [['DELETE',{id:'contact'}],['PATCH',{id:'contact',action:'restore'}]]){const h=harness(config);assert.equal((await h.run(method,body)).status,409)}});
test('normal read and update exclude Trash',async()=>{for(const [method,body] of [['GET',null],['PATCH',{id:'contact',notes:'hello'}]]){const h=harness();await h.run(method,body);assert.ok(h.calls.some(c=>c[0]==='is'&&c[1]==='deleted_at'&&c[2]===null))}});
test('a restore request cannot also modify other fields',async()=>{const h=harness();assert.equal((await h.run('PATCH',{id:'contact',action:'restore',notes:'changed'})).status,400);assert.equal(h.calls.length,0)});
