const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const moduleValue={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/follow-up.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:moduleValue,exports:moduleValue.exports,Date});const {schedulingPatch}=moduleValue.exports;
function harness({missing=false,error=false}={}){
 const old={id:'1',column:'today',status:'due-today',statusLabel:'Follow up today',sentDate:'',activity:[]};let stored={id:'1',sent_date:'',column_name:'today'},state=[old],selected=old;const writes=[],toasts=[],scopes=[];
 const chain={update(patch){writes.push(patch);if(!missing&&!error)stored={...stored,...patch};return chain},eq(...args){scopes.push(args);return chain},select(){return chain},async maybeSingle(){return{data:missing?null:stored,error:error?{message:'failed'}:null}}};
 const source=fs.readFileSync('app/page.tsx','utf8');const start=source.indexOf('  const handleUpdateContact =');const end=source.indexOf('\n  }, [contacts,user])',start)+'\n  }, [contacts,user])'.length;
 const code=ts.transpileModule(source.slice(start,end)+'\nexport {handleUpdateContact}',{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const m={exports:{}};vm.runInNewContext(code,{module:m,exports:m.exports,user:{id:'owner'},contacts:[old],schedulingPatch,useCallback:f=>f,supabase:{from:()=>chain},setToast:t=>toasts.push(t),setContacts:f=>state=f(state),setSelected:f=>selected=f(selected),console:{error(){}}});return{run:m.exports.handleUpdateContact,writes,toasts,scopes,get stored(){return stored},get state(){return state}};
}
test('activity-only write never restores the old follow-up date',async()=>{const h=harness();assert.equal(await h.run('1',{column:'upcoming',sentDate:'2099-09-28',activity:['scheduled']}),true);assert.equal(await h.run('1',{activity:['scheduled','updated']}),true);assert.equal(h.stored.sent_date,'2099-09-28');assert.equal(h.stored.column_name,'upcoming');assert.equal(h.writes[1].sent_date,undefined);assert.equal(h.writes[1].column_name,undefined)});
test('date, stage and activity persist in one owner-scoped write',async()=>{const h=harness();await h.run('1',{column:'upcoming',sentDate:'2099-09-28',activity:['scheduled']});assert.equal(h.writes.length,1);assert.equal(h.stored.sent_date,'2099-09-28');assert.equal(h.stored.activity[0],'scheduled');assert.ok(h.scopes.some(s=>s[0]==='user_id'&&s[1]==='owner'))});
test('missing row or failed write cannot falsely report success',async()=>{for(const config of [{missing:true},{error:true}]){const h=harness(config);assert.equal(await h.run('1',{sentDate:'2099-09-28'}),false);assert.equal(h.state[0].sentDate,'')}});
test('notes and email edits do not touch a saved schedule',()=>{for(const patch of [{notes:'Updated'},{email:'new@example.com'},{activity:['entry']}]){const result=schedulingPatch({column:'today',sentDate:''},patch);assert.equal(result.sentDate,undefined);assert.equal(result.column,undefined)}});
test('invalid follow-up dates are rejected before writing',async()=>{const h=harness();assert.equal(await h.run('1',{sentDate:'2026-02-30'}),false);assert.equal(h.writes.length,0)});
