'use client'
import { useState } from 'react'
import { Contact } from '@/types'
import { supabase } from '@/lib/supabase'
import ContactPhoto from './ContactPhoto'
import EmailStatusBadge from './EmailStatusBadge'
interface Props { contacts: Contact[]; onSelect:(c:Contact)=>void; onUpdateContact:(id:string,u:Partial<Contact>)=>Promise<boolean> }
export default function EnrichmentView({contacts,onSelect,onUpdateContact}:Props) {
 const [busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState(''),[query,setQuery]=useState('')
 const [filter,setFilter]=useState('all')
 const visible=contacts.filter(c=>[c.firstName,c.lastName,c.company,c.email].join(' ').toLowerCase().includes(query.toLowerCase()) && (filter==='all'||filter==='missing'&&!c.email||filter==='review'&&!!c.email&&c.emailStatus!=='valid'))
 async function run(c:Contact,action='find') {
  setBusy(String(c.id));setMessage('')
  try {
   const {data:{session}}=await supabase.auth.getSession()
   const res=await fetch('/api/enrich',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session?.access_token},body:JSON.stringify({contactId:c.id,action,allowPaid:true})})
   const data=await res.json()
   if(!res.ok) throw new Error(data.error||'Lookup failed')
   if(data.email) {
    const saved=await onUpdateContact(c.id,{email:data.email,enriched:true,emailStatus:data.emailStatus,emailSource:data.emailSource,emailCheckedAt:data.emailCheckedAt,emailEvidence:data.emailEvidence})
    if(!saved) throw new Error('Could not refresh contact')
    setMessage('Result saved. 1 email credit used.')
   } else setMessage(data.message||'No result found')
  }catch(e){setMessage(e instanceof Error?e.message:'Lookup failed')}finally{setBusy(null)}
 }
 const counts={all:contacts.length,missing:contacts.filter(c=>!c.email).length,review:contacts.filter(c=>c.email&&c.emailStatus!=='valid').length}
 return <section className="max-w-[1440px] mx-auto p-4 sm:p-6 lg:p-8 space-y-6">
  <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3.5"><div className="w-12 h-12 rounded-2xl bg-blue-100 text-blue-600 flex items-center justify-center"><svg aria-hidden="true" className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 7 9 6 9-6"/></svg></div><div><h2 className="text-2xl font-bold text-slate-900 tracking-tight">Email finder</h2><p className="text-sm text-slate-500 mt-1">The right address for your next conversation.</p></div></div><div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-2.5"><p className="text-xs font-semibold text-blue-700">1 credit per email found</p><p className="text-[11px] text-blue-500 mt-0.5">No result, no charge.</p></div></header>
  <div className="grid sm:grid-cols-3 gap-3">{[{key:'all',label:'All contacts',value:counts.all,color:'bg-blue-50 text-blue-700'},{key:'missing',label:'Missing an email',value:counts.missing,color:'bg-amber-50 text-amber-700'},{key:'review',label:'Ready for review',value:counts.review,color:'bg-violet-50 text-violet-700'}].map(stat=><button key={stat.key} onClick={()=>setFilter(stat.key)} aria-pressed={filter===stat.key} className={'flex items-center justify-between gap-3 rounded-2xl border bg-white px-5 py-4 shadow-sm text-left transition hover:border-blue-200 '+(filter===stat.key?'border-blue-200 ring-1 ring-blue-100':'border-slate-100')}><p className="text-xs font-semibold text-slate-500">{stat.label}</p><span className={'rounded-xl px-3 py-1.5 text-xl font-bold '+stat.color}>{stat.value}</span></button>)}</div>
  {message&&<p role="status" className="px-4 py-3 border border-blue-100 bg-blue-50 text-blue-800 rounded-xl text-sm">{message}</p>}
  <div className="bg-white border border-slate-100 rounded-2xl shadow-sm overflow-hidden">
   <div className="p-4 sm:p-5 flex flex-wrap items-center justify-between gap-4 border-b border-slate-100"><div><h3 className="text-sm font-bold text-slate-900">Contact directory</h3><p className="text-xs text-slate-400 mt-1">{visible.length} {visible.length===1?'contact':'contacts'} in this view</p></div><div className="relative w-full sm:w-72"><svg aria-hidden="true" className="w-4 h-4 absolute left-3 top-3 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input aria-label="Search email contacts" className="w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 py-2.5 text-xs outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-50" placeholder="Search name, company or email" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
   <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50/80 text-left"><tr>{['Contact','Company','Work email','Status',''].map((h,i)=><th key={i} scope="col" className="px-5 py-3 text-[10px] font-bold text-slate-400 uppercase tracking-widest">{h||<span className="sr-only">Actions</span>}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map(c=><tr key={c.id} className="hover:bg-slate-50/60 transition-colors"><td className="px-5 py-4"><button onClick={()=>onSelect(c)} className="flex items-center gap-3 text-left group"><span className="w-9 h-9 rounded-xl flex items-center justify-center text-xs font-bold text-white shrink-0 overflow-hidden" style={{background:c.avatarColor||'#2563eb'}}><ContactPhoto url={c.photoUrl} initials={(c.firstName[0]||'')+(c.lastName[0]||'')} name={c.firstName+' '+c.lastName}/></span><span className="min-w-[130px]"><span className="block text-[13px] text-slate-900 font-semibold group-hover:text-blue-600">{c.firstName} {c.lastName}</span><span className="block text-[11px] text-slate-400 mt-0.5 max-w-[220px] truncate">{c.jobTitle||'Open contact'}</span></span></button></td><td className="px-5 py-4 text-xs font-medium text-slate-600">{c.company||'Not added'}</td><td className="px-5 py-4 text-xs text-slate-600 break-all">{c.email||<span className="text-slate-400">Ready to find</span>}</td><td className="px-5 py-4"><EmailStatusBadge contact={c}/></td><td className="px-5 py-4"><button disabled={!!busy} onClick={()=>run(c,c.email?'verify':'find')} className={'whitespace-nowrap rounded-xl px-3.5 py-2.5 text-xs font-semibold transition disabled:opacity-50 '+(c.email?'border border-slate-200 text-slate-600 bg-white hover:bg-slate-50':'bg-blue-600 text-white shadow-sm hover:bg-blue-700')}>{busy===String(c.id)?'Searching…':c.email?'Verify (1 credit)':'Find email (1 credit)'}</button></td></tr>)}</tbody></table></div>
   {!visible.length&&<div className="py-16 px-6 text-center"><div className="mx-auto w-12 h-12 rounded-2xl bg-blue-50 text-blue-500 flex items-center justify-center text-xl mb-4" aria-hidden="true">⌕</div><h3 className="text-sm font-bold text-slate-800">{!contacts.length?'Your next connection starts here':'No contacts in this view'}</h3><p className="text-xs text-slate-400 mt-2 max-w-sm mx-auto leading-5">{!contacts.length?'Add contacts to your CRM or capture a profile with the Hirely extension. Then find their work emails here.':'Try a different search or return to all contacts.'}</p>{!!contacts.length&&<button onClick={()=>{setQuery('');setFilter('all')}} className="mt-4 text-xs font-semibold text-blue-600 hover:underline">Show all contacts</button>}</div>}
  </div>
  <p className="text-[11px] text-slate-400 leading-5">Verification costs 1 credit per completed result. Review the email status before outreach.</p>
 </section>
}
