import { Contact, AIDraft } from '@/types'

export const mockContacts: Contact[] = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Kim',
    email: 's.kim@rogers.com',
    phone: '+1 416 555 0192',
    company: 'Rogers Communications',
    jobTitle: 'HR Director',
    linkedinUrl: 'linkedin.com/in/sarah-kim',
    avatarColor: '#2563EB',
    status: 'overdue',
    column: 'today',
    statusLabel: 'Overdue 2d',
    sentDate: '2 weeks ago',
    originalEmail: 'Hi Sarah, I wanted to reach out about potential engineering placement opportunities at Rogers. We have some exceptional senior candidates who would be a great fit for your team.',
    enriched: true,
    activity: ['Email sent 2 weeks ago', 'LinkedIn profile enriched via Hunter.io', 'Outlook add-in captured contact'],
    notes: ''
  },
  {
    id: '2',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'm.johnson@td.com',
    phone: '+1 416 555 0143',
    company: 'TD Bank',
    jobTitle: 'Talent Acquisition Manager',
    linkedinUrl: 'linkedin.com/in/mike-johnson-td',
    avatarColor: '#7C3AED',
    status: 'due-today',
    column: 'today',
    statusLabel: 'Due today',
    sentDate: '2 weeks ago',
    originalEmail: 'Hi Mike, following up on our conversation about senior engineering roles at TD. We have 3 strong candidates ready for interviews this month.',
    enriched: true,
    activity: ['Email sent 2 weeks ago', 'Reminder set for today', 'LinkedIn enriched via Hunter.io'],
    notes: ''
  },
  {
    id: '3',
    firstName: 'Aisha',
    lastName: 'Patel',
    email: 'a.patel@shopify.com',
    phone: '+1 416 555 0167',
    company: 'Shopify',
    jobTitle: 'People Lead',
    linkedinUrl: 'linkedin.com/in/aisha-patel',
    avatarColor: '#D97706',
    status: 'due-today',
    column: 'today',
    statusLabel: 'Due today',
    sentDate: '13 days ago',
    originalEmail: 'Hi Aisha, reaching out regarding senior developer positions on your team. We specialize in placing top-tier engineering talent in fast-growing tech companies.',
    enriched: true,
    activity: ['Email sent 13 days ago', 'Company data enriched', 'Follow-up due today'],
    notes: ''
  },
  {
    id: '4',
    firstName: 'Lisa',
    lastName: 'Rodriguez',
    email: 'l.rodriguez@bell.ca',
    phone: '+1 416 555 0128',
    company: 'Bell Canada',
    jobTitle: 'HR Manager',
    linkedinUrl: 'linkedin.com/in/lisa-rodriguez-bell',
    avatarColor: '#059669',
    status: 'upcoming',
    column: 'upcoming',
    statusLabel: 'In 3 days',
    sentDate: '11 days ago',
    originalEmail: 'Hi Lisa, connecting about Q3 talent acquisition needs at Bell Canada. Our team has great candidates in telecom and tech.',
    enriched: true,
    activity: ['Email sent 11 days ago', 'Follow-up scheduled in 3 days', 'LinkedIn enriched'],
    notes: ''
  },
  {
    id: '5',
    firstName: 'Tom',
    lastName: 'Chen',
    email: 't.chen@rbc.com',
    phone: '+1 416 555 0155',
    company: 'RBC',
    jobTitle: 'Recruiter',
    linkedinUrl: 'linkedin.com/in/tom-chen-rbc',
    avatarColor: '#DC2626',
    status: 'upcoming',
    column: 'upcoming',
    statusLabel: 'In 5 days',
    sentDate: '9 days ago',
    originalEmail: 'Hi Tom, reaching out about financial services talent. We have strong candidates in fintech and banking ready to interview.',
    enriched: true,
    activity: ['Email sent 9 days ago', 'Follow-up in 5 days'],
    notes: ''
  },
  {
    id: '6',
    firstName: 'Nina',
    lastName: 'Watson',
    email: 'n.watson@cibc.com',
    phone: '+1 416 555 0189',
    company: 'CIBC',
    jobTitle: 'TA Lead',
    linkedinUrl: 'linkedin.com/in/nina-watson-cibc',
    avatarColor: '#0891B2',
    status: 'upcoming',
    column: 'upcoming',
    statusLabel: 'In 1 week',
    sentDate: '7 days ago',
    originalEmail: 'Hi Nina, I have exceptional banking and tech candidates who would be a great fit for CIBC roles this quarter.',
    enriched: false,
    activity: ['Email sent 7 days ago', 'Auto follow-up scheduled'],
    notes: ''
  },
  {
    id: '7',
    firstName: 'Ben',
    lastName: 'Miller',
    email: 'b.miller@scotiabank.com',
    phone: '+1 416 555 0177',
    company: 'Scotiabank',
    jobTitle: 'HR Director',
    linkedinUrl: 'linkedin.com/in/ben-miller-scotia',
    avatarColor: '#7C3AED',
    status: 'upcoming',
    column: 'upcoming',
    statusLabel: 'In 2 weeks',
    sentDate: '2 days ago',
    originalEmail: 'Hi Ben, reaching out about strategic hiring at Scotiabank. Senior finance and tech candidates ready for your team.',
    enriched: true,
    activity: ['Email sent 2 days ago', 'LinkedIn profile saved'],
    notes: ''
  },
  {
    id: '8',
    firstName: 'James',
    lastName: 'Lee',
    email: 'j.lee@amazon.com',
    phone: '+1 416 555 0134',
    company: 'Amazon Canada',
    jobTitle: 'HR Manager',
    linkedinUrl: 'linkedin.com/in/james-lee-amazon',
    avatarColor: '#16A34A',
    status: 'replied',
    column: 'done',
    statusLabel: 'Replied',
    sentDate: '3 weeks ago',
    originalEmail: 'Hi James, reaching out about warehouse operations and tech hiring needs at Amazon Canada.',
    enriched: true,
    activity: ['Replied yesterday - interested', 'Meeting requested', 'Follow-up sequence paused automatically'],
    notes: 'Interested in 2 senior DevOps engineers. Following up next week.'
  },
  {
    id: '9',
    firstName: 'Fatima',
    lastName: 'Shah',
    email: 'f.shah@google.com',
    phone: '+1 416 555 0198',
    company: 'Google Canada',
    jobTitle: 'People Operations',
    linkedinUrl: 'linkedin.com/in/fatima-shah-google',
    avatarColor: '#16A34A',
    status: 'meeting-set',
    column: 'done',
    statusLabel: 'Meeting set',
    sentDate: '3 weeks ago',
    originalEmail: 'Hi Fatima, connecting about software engineering roles at Google Canada. Top-tier candidates with strong ML backgrounds.',
    enriched: true,
    activity: ['Meeting set for next Tuesday', 'Replied within 3 days', 'Sequence paused - success'],
    notes: 'Meeting Tuesday 2pm. She wants ML engineers with 5+ years experience.'
  },
  {
    id: '10',
    firstName: 'David',
    lastName: 'Kim',
    email: 'd.kim@microsoft.com',
    phone: 'Not found',
    company: 'Microsoft',
    jobTitle: 'TA Manager',
    linkedinUrl: 'linkedin.com/in/david-kim-msft',
    avatarColor: '#6B7280',
    status: 'no-response',
    column: 'done',
    statusLabel: 'No response',
    sentDate: '1 month ago',
    originalEmail: 'Hi David, reaching out about engineering talent for Microsoft Canada teams.',
    enriched: true,
    activity: ['Email sent 1 month ago', '2 follow-ups sent', 'Marked as no response'],
    notes: ''
  }
]

export function getAIDrafts(contact: Contact): AIDraft[] {
  const firstName = contact.firstName
  const company = contact.company
  return [
    {
      id: '1',
      label: '2-week follow-up',
      timing: '2 weeks',
      body: `Hi ${firstName}, I wanted to follow up on my previous email about placement opportunities at ${company}. We have had great success placing candidates in similar roles this quarter and would love to explore how we can support your team. Would you have 15 minutes for a quick call this week?`
    },
    {
      id: '2',
      label: '1-month follow-up',
      timing: '1 month',
      body: `Hi ${firstName}, checking back in as we head into next month. Our team has placed 12 candidates in similar roles recently. If the timing is better now, I would love to share more details - even a 10-minute call would be helpful.`
    },
    {
      id: '3',
      label: 'Final attempt',
      timing: 'Final',
      body: `Hi ${firstName}, keeping this short. We have a strong candidate who would genuinely be a great fit at ${company}. If there is any interest, just reply with a thumbs up and I will send the profile over. No commitment needed.`
    }
  ]
}

export const avatarColors = [
  '#2563EB', '#7C3AED', '#D97706', '#059669',
  '#DC2626', '#0891B2', '#BE185D', '#065F46'
]
